name: ItemFilter
version: ${version}
main: me.pustinek.itemfilter.ItemFilterPlugin
api-version: 1.13
authors: [Pustinek]
description: Minecraft item filter plugin
commands:
  itemfilter:
    description: 'for all the commands use /ItemFilter help'
    usage: '/itemfilter'
    aliases: [filter, if]
permissions:
  itemfilter.*:
    description: 'Give access to all commands of itemfilter'
    default: op
    children:
      itemfilter.use: true
      itemfilter.reload: true
  itemfilter.use:
    description: "Basic usage of the plugin"
    default: op
  itemfilter.reload:
    description: "Reload the plugin"
    default: op