no_perms: "&cInsufficient permissions"
invalid_command: "&cInvalid command"
invalid_material:  "&cInvalid material"
help_header: "&7┅┅┅┅┅┅┅┅┅┅┅[ItemFilter]┅┅┅┅┅┅┅┅┅┅┅"
help_reload: "&6/itemfilter reload &f- reload configuration"
help_menu: "&6/itemfilter menu &f- Open menu GUI"
help_add: "&6/itemfilter add &f- add item in hand to filter"
help_remove:  "&6/itemfilter remove &f- remove item in hand from filter"
help_reset: "&6/itemfilter reset &f- reset all your item filters"
help_toggle: "&6/itemfilter toggle &f- toggle filter"
help_footer: "&7┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅┅"

reload_success: "&2Successfully reloaded config files."

reset_success: "&2Successfully reset your filtered items."

filter_on: "filter is now &2ON"
filter_off: "filter is now &cOFF"
filter_add: "&fSuccessfully &2Added &f%0% &fto the filter"
filter_remove: "&fSuccessfully &cRemoved &f%0%  &ffrom the filter"